// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MS.WebSite.Controllers
{
    public partial class UserAreaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserAreaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Records()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Records);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ChangeTrainingStatus()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ChangeTrainingStatus);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Pay()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Pay);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PayBySubscriptionId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PayBySubscriptionId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetSubscriptionPrice()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSubscriptionPrice);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Subscriptions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Subscriptions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyTrainingRecords()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyTrainingRecords);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ResumeSubscription()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResumeSubscription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ActivateSubscription()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ActivateSubscription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RemoveExpiredSubscription()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveExpiredSubscription);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CancelTrainingRecord()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CancelTrainingRecord);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserAreaController Actions { get { return MVC.UserArea; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "UserArea";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "UserArea";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ClientInfo = "ClientInfo";
            public readonly string TrainerInfo = "TrainerInfo";
            public readonly string EditInfo = "EditInfo";
            public readonly string Records = "Records";
            public readonly string ChangeTrainingStatus = "ChangeTrainingStatus";
            public readonly string Buy = "Buy";
            public readonly string Pay = "Pay";
            public readonly string PayBySubscriptionId = "PayBySubscriptionId";
            public readonly string Success = "Success";
            public readonly string Error = "Error";
            public readonly string GetSubscriptionPrice = "GetSubscriptionPrice";
            public readonly string Subscriptions = "Subscriptions";
            public readonly string NewTrainingRecord = "NewTrainingRecord";
            public readonly string MyTrainingRecords = "MyTrainingRecords";
            public readonly string SubscriptionFreeze = "SubscriptionFreeze";
            public readonly string ECard = "ECard";
            public readonly string ResumeSubscription = "ResumeSubscription";
            public readonly string ActivateSubscription = "ActivateSubscription";
            public readonly string RemoveExpiredSubscription = "RemoveExpiredSubscription";
            public readonly string CancelTrainingRecord = "CancelTrainingRecord";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ClientInfo = "ClientInfo";
            public const string TrainerInfo = "TrainerInfo";
            public const string EditInfo = "EditInfo";
            public const string Records = "Records";
            public const string ChangeTrainingStatus = "ChangeTrainingStatus";
            public const string Buy = "Buy";
            public const string Pay = "Pay";
            public const string PayBySubscriptionId = "PayBySubscriptionId";
            public const string Success = "Success";
            public const string Error = "Error";
            public const string GetSubscriptionPrice = "GetSubscriptionPrice";
            public const string Subscriptions = "Subscriptions";
            public const string NewTrainingRecord = "NewTrainingRecord";
            public const string MyTrainingRecords = "MyTrainingRecords";
            public const string SubscriptionFreeze = "SubscriptionFreeze";
            public const string ECard = "ECard";
            public const string ResumeSubscription = "ResumeSubscription";
            public const string ActivateSubscription = "ActivateSubscription";
            public const string RemoveExpiredSubscription = "RemoveExpiredSubscription";
            public const string CancelTrainingRecord = "CancelTrainingRecord";
        }


        static readonly ActionParamsClass_EditInfo s_params_EditInfo = new ActionParamsClass_EditInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditInfo EditInfoParams { get { return s_params_EditInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditInfo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Records s_params_Records = new ActionParamsClass_Records();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Records RecordsParams { get { return s_params_Records; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Records
        {
            public readonly string page = "page";
            public readonly string filter = "filter";
        }
        static readonly ActionParamsClass_ChangeTrainingStatus s_params_ChangeTrainingStatus = new ActionParamsClass_ChangeTrainingStatus();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeTrainingStatus ChangeTrainingStatusParams { get { return s_params_ChangeTrainingStatus; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeTrainingStatus
        {
            public readonly string trainingId = "trainingId";
            public readonly string statusId = "statusId";
        }
        static readonly ActionParamsClass_Buy s_params_Buy = new ActionParamsClass_Buy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Buy BuyParams { get { return s_params_Buy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Buy
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Pay s_params_Pay = new ActionParamsClass_Pay();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Pay PayParams { get { return s_params_Pay; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Pay
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PayBySubscriptionId s_params_PayBySubscriptionId = new ActionParamsClass_PayBySubscriptionId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PayBySubscriptionId PayBySubscriptionIdParams { get { return s_params_PayBySubscriptionId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PayBySubscriptionId
        {
            public readonly string subscriptionId = "subscriptionId";
        }
        static readonly ActionParamsClass_GetSubscriptionPrice s_params_GetSubscriptionPrice = new ActionParamsClass_GetSubscriptionPrice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSubscriptionPrice GetSubscriptionPriceParams { get { return s_params_GetSubscriptionPrice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSubscriptionPrice
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Subscriptions s_params_Subscriptions = new ActionParamsClass_Subscriptions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Subscriptions SubscriptionsParams { get { return s_params_Subscriptions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Subscriptions
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_NewTrainingRecord s_params_NewTrainingRecord = new ActionParamsClass_NewTrainingRecord();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewTrainingRecord NewTrainingRecordParams { get { return s_params_NewTrainingRecord; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewTrainingRecord
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_MyTrainingRecords s_params_MyTrainingRecords = new ActionParamsClass_MyTrainingRecords();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyTrainingRecords MyTrainingRecordsParams { get { return s_params_MyTrainingRecords; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyTrainingRecords
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_SubscriptionFreeze s_params_SubscriptionFreeze = new ActionParamsClass_SubscriptionFreeze();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubscriptionFreeze SubscriptionFreezeParams { get { return s_params_SubscriptionFreeze; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubscriptionFreeze
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ResumeSubscription s_params_ResumeSubscription = new ActionParamsClass_ResumeSubscription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResumeSubscription ResumeSubscriptionParams { get { return s_params_ResumeSubscription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResumeSubscription
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_ActivateSubscription s_params_ActivateSubscription = new ActionParamsClass_ActivateSubscription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActivateSubscription ActivateSubscriptionParams { get { return s_params_ActivateSubscription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActivateSubscription
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RemoveExpiredSubscription s_params_RemoveExpiredSubscription = new ActionParamsClass_RemoveExpiredSubscription();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveExpiredSubscription RemoveExpiredSubscriptionParams { get { return s_params_RemoveExpiredSubscription; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveExpiredSubscription
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CancelTrainingRecord s_params_CancelTrainingRecord = new ActionParamsClass_CancelTrainingRecord();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CancelTrainingRecord CancelTrainingRecordParams { get { return s_params_CancelTrainingRecord; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CancelTrainingRecord
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _RecordsTable = "_RecordsTable";
                public readonly string Buy = "Buy";
                public readonly string ClientInfo = "ClientInfo";
                public readonly string ClientMenu = "ClientMenu";
                public readonly string ECard = "ECard";
                public readonly string EditInfo = "EditInfo";
                public readonly string Index = "Index";
                public readonly string MyTrainingRecords = "MyTrainingRecords";
                public readonly string NewTrainingRecord = "NewTrainingRecord";
                public readonly string Pay = "Pay";
                public readonly string Records = "Records";
                public readonly string Status = "Status";
                public readonly string SubscriptionFreeze = "SubscriptionFreeze";
                public readonly string Subscriptions = "Subscriptions";
                public readonly string TrainerInfo = "TrainerInfo";
                public readonly string TrainerMenu = "TrainerMenu";
                public readonly string TrainingRecordsSearch = "TrainingRecordsSearch";
            }
            public readonly string _RecordsTable = "~/Views/UserArea/_RecordsTable.cshtml";
            public readonly string Buy = "~/Views/UserArea/Buy.cshtml";
            public readonly string ClientInfo = "~/Views/UserArea/ClientInfo.cshtml";
            public readonly string ClientMenu = "~/Views/UserArea/ClientMenu.cshtml";
            public readonly string ECard = "~/Views/UserArea/ECard.cshtml";
            public readonly string EditInfo = "~/Views/UserArea/EditInfo.cshtml";
            public readonly string Index = "~/Views/UserArea/Index.cshtml";
            public readonly string MyTrainingRecords = "~/Views/UserArea/MyTrainingRecords.cshtml";
            public readonly string NewTrainingRecord = "~/Views/UserArea/NewTrainingRecord.cshtml";
            public readonly string Pay = "~/Views/UserArea/Pay.cshtml";
            public readonly string Records = "~/Views/UserArea/Records.cshtml";
            public readonly string Status = "~/Views/UserArea/Status.cshtml";
            public readonly string SubscriptionFreeze = "~/Views/UserArea/SubscriptionFreeze.cshtml";
            public readonly string Subscriptions = "~/Views/UserArea/Subscriptions.cshtml";
            public readonly string TrainerInfo = "~/Views/UserArea/TrainerInfo.cshtml";
            public readonly string TrainerMenu = "~/Views/UserArea/TrainerMenu.cshtml";
            public readonly string TrainingRecordsSearch = "~/Views/UserArea/TrainingRecordsSearch.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserAreaController : MS.WebSite.Controllers.UserAreaController
    {
        public T4MVC_UserAreaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClientInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClientInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClientInfo);
            ClientInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TrainerInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TrainerInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TrainerInfo);
            TrainerInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditInfo);
            EditInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MS.Models.Models.EditInfoViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditInfo(MS.Models.Models.EditInfoViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditInfoOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void RecordsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, string filter);

        [NonAction]
        public override System.Web.Mvc.ActionResult Records(int? page, string filter)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Records);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filter", filter);
            RecordsOverride(callInfo, page, filter);
            return callInfo;
        }

        [NonAction]
        partial void ChangeTrainingStatusOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string trainingId, string statusId);

        [NonAction]
        public override System.Web.Mvc.JsonResult ChangeTrainingStatus(string trainingId, string statusId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ChangeTrainingStatus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trainingId", trainingId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "statusId", statusId);
            ChangeTrainingStatusOverride(callInfo, trainingId, statusId);
            return callInfo;
        }

        [NonAction]
        partial void BuyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Buy()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Buy);
            BuyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BuyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MS.Models.Models.BuyViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Buy(MS.Models.Models.BuyViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Buy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            BuyOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Pay(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Pay);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PayOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PayBySubscriptionIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int subscriptionId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PayBySubscriptionId(int subscriptionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PayBySubscriptionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "subscriptionId", subscriptionId);
            PayBySubscriptionIdOverride(callInfo, subscriptionId);
            return callInfo;
        }

        [NonAction]
        partial void SuccessOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Success()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Success);
            SuccessOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ErrorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Error()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
            ErrorOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetSubscriptionPriceOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetSubscriptionPrice(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSubscriptionPrice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetSubscriptionPriceOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SubscriptionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Subscriptions(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Subscriptions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            SubscriptionsOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void NewTrainingRecordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewTrainingRecord()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewTrainingRecord);
            NewTrainingRecordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewTrainingRecordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MS.Models.Models.NewTrainingModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewTrainingRecord(MS.Models.Models.NewTrainingModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewTrainingRecord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NewTrainingRecordOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void MyTrainingRecordsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyTrainingRecords(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyTrainingRecords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            MyTrainingRecordsOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void SubscriptionFreezeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SubscriptionFreeze()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubscriptionFreeze);
            SubscriptionFreezeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SubscriptionFreezeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MS.Models.Models.SubscriptionFreezeViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SubscriptionFreeze(MS.Models.Models.SubscriptionFreezeViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubscriptionFreeze);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SubscriptionFreezeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ECardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ECard()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ECard);
            ECardOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResumeSubscriptionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ResumeSubscription(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResumeSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ResumeSubscriptionOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void ActivateSubscriptionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ActivateSubscription(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ActivateSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ActivateSubscriptionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RemoveExpiredSubscriptionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult RemoveExpiredSubscription(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveExpiredSubscription);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoveExpiredSubscriptionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CancelTrainingRecordOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult CancelTrainingRecord(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CancelTrainingRecord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CancelTrainingRecordOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
