// <auto-generated />
namespace MS.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstnutellamigrationtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstnutellamigrationtest));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151605300_first nutella migration test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
