//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate subscription.
        /// </summary>
        public static string ActivateSubscription {
            get {
                return ResourceManager.GetString("ActivateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do toy want activate your subscription?.
        /// </summary>
        public static string ActivateSubscriptionQuestion {
            get {
                return ResourceManager.GetString("ActivateSubscriptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Record.
        /// </summary>
        public static string AddRecord {
            get {
                return ResourceManager.GetString("AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy new subscription.
        /// </summary>
        public static string BuyNewSubscription {
            get {
                return ResourceManager.GetString("BuyNewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy subscription.
        /// </summary>
        public static string BuySubscription {
            get {
                return ResourceManager.GetString("BuySubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not have more than tree active subscriptions.
        /// </summary>
        public static string BySubscriptionError {
            get {
                return ResourceManager.GetString("BySubscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelRecord {
            get {
                return ResourceManager.GetString("CancelRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want cancel your training record?.
        /// </summary>
        public static string CancelRecordQuestion {
            get {
                return ResourceManager.GetString("CancelRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose time.
        /// </summary>
        public static string ChooseTime {
            get {
                return ResourceManager.GetString("ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose who are you.
        /// </summary>
        public static string ChooseWhoAreYou {
            get {
                return ResourceManager.GetString("ChooseWhoAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club card number.
        /// </summary>
        public static string ClubCardNumber {
            get {
                return ResourceManager.GetString("ClubCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subscription.
        /// </summary>
        public static string DeleteSubscription {
            get {
                return ResourceManager.GetString("DeleteSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this subscription?.
        /// </summary>
        public static string DeleteSubscriptionQuestion {
            get {
                return ResourceManager.GetString("DeleteSubscriptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don`t have account?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Card.
        /// </summary>
        public static string ECard {
            get {
                return ResourceManager.GetString("ECard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your info.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your data.
        /// </summary>
        public static string EditYourData {
            get {
                return ResourceManager.GetString("EditYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Enum_EGenderType_Female {
            get {
                return ResourceManager.GetString("Enum_EGenderType_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Enum_EGenderType_Male {
            get {
                return ResourceManager.GetString("Enum_EGenderType_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Enum_EPaymentStatus_Error {
            get {
                return ResourceManager.GetString("Enum_EPaymentStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Enum_EPaymentStatus_New {
            get {
                return ResourceManager.GetString("Enum_EPaymentStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Enum_EPaymentStatus_Success {
            get {
                return ResourceManager.GetString("Enum_EPaymentStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Enum_ESubscriptionStatus_Active {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Enum_ESubscriptionStatus_Expired {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        public static string Enum_ESubscriptionStatus_Frozen {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Enum_ESubscriptionStatus_New {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active.
        /// </summary>
        public static string Enum_ESubscriptionStatus_NoActive {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_NoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Enum_ESubscriptionStatus_Payed {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionStatus_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day one month.
        /// </summary>
        public static string Enum_ESubscriptionType_AllDayOneMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_AllDayOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day six month.
        /// </summary>
        public static string Enum_ESubscriptionType_AllDaySixMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_AllDaySixMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day three month.
        /// </summary>
        public static string Enum_ESubscriptionType_AllDayThreeMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_AllDayThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day time one month.
        /// </summary>
        public static string Enum_ESubscriptionType_DayTimeOneMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_DayTimeOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day time six month.
        /// </summary>
        public static string Enum_ESubscriptionType_DayTimeSixMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_DayTimeSixMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day time three month.
        /// </summary>
        public static string Enum_ESubscriptionType_DayTimeThreeMonth {
            get {
                return ResourceManager.GetString("Enum_ESubscriptionType_DayTimeThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Enum_ETrainingRecordStatus_Closed {
            get {
                return ResourceManager.GetString("Enum_ETrainingRecordStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Enum_ETrainingRecordStatus_New {
            get {
                return ResourceManager.GetString("Enum_ETrainingRecordStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Enum_ETrainingRecordStatus_Payed {
            get {
                return ResourceManager.GetString("Enum_ETrainingRecordStatus_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpayed.
        /// </summary>
        public static string Enum_ETrainingRecordStatus_Unpayed {
            get {
                return ResourceManager.GetString("Enum_ETrainingRecordStatus_Unpayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error data.
        /// </summary>
        public static string Error_inputErrorData {
            get {
                return ResourceManager.GetString("Error_inputErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and password incorect.
        /// </summary>
        public static string Error_LoginAndPasswordIncorect {
            get {
                return ResourceManager.GetString("Error_LoginAndPasswordIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no place on this hour.
        /// </summary>
        public static string Error_ManyTrainerRecords {
            get {
                return ResourceManager.GetString("Error_ManyTrainerRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can`t have more than one active training record.
        /// </summary>
        public static string Error_ManyUserTrainingRecords {
            get {
                return ResourceManager.GetString("Error_ManyUserTrainingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select subscription type.
        /// </summary>
        public static string Error_SelectSubscriptionType {
            get {
                return ResourceManager.GetString("Error_SelectSubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        public static string Error_SomethingWrong {
            get {
                return ResourceManager.GetString("Error_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file extension, allowed: jpg, jpeg, png, gif.
        /// </summary>
        public static string ErrorExtension {
            get {
                return ResourceManager.GetString("ErrorExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to large, must be less then 2mb.
        /// </summary>
        public static string ErrorSize {
            get {
                return ResourceManager.GetString("ErrorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze from.
        /// </summary>
        public static string FreezeFrom {
            get {
                return ResourceManager.GetString("FreezeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze subscription.
        /// </summary>
        public static string FreezeSubscription {
            get {
                return ResourceManager.GetString("FreezeSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze to.
        /// </summary>
        public static string FreezeTo {
            get {
                return ResourceManager.GetString("FreezeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back home.
        /// </summary>
        public static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left freeze days.
        /// </summary>
        public static string LeftFreezeDays {
            get {
                return ResourceManager.GetString("LeftFreezeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left frozen days.
        /// </summary>
        public static string LeftFrozenDays {
            get {
                return ResourceManager.GetString("LeftFrozenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main portal.
        /// </summary>
        public static string MainPortal {
            get {
                return ResourceManager.GetString("MainPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription freeze.
        /// </summary>
        public static string Menu_SubscriptionFreeze {
            get {
                return ResourceManager.GetString("Menu_SubscriptionFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My training records.
        /// </summary>
        public static string MyRecords {
            get {
                return ResourceManager.GetString("MyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My subscriptions.
        /// </summary>
        public static string MySubscriptions {
            get {
                return ResourceManager.GetString("MySubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My training records.
        /// </summary>
        public static string MyTrainingRecords {
            get {
                return ResourceManager.GetString("MyTrainingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New training record.
        /// </summary>
        public static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New training record.
        /// </summary>
        public static string NewTrainingRecord {
            get {
                return ResourceManager.GetString("NewTrainingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don`t have active subscription.
        /// </summary>
        public static string NoActiveSubscription {
            get {
                return ResourceManager.GetString("NoActiveSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don`t have subscriptions.
        /// </summary>
        public static string NoSubscriptions {
            get {
                return ResourceManager.GetString("NoSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        public static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our trainers.
        /// </summary>
        public static string OurTrainers {
            get {
                return ResourceManager.GetString("OurTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match.
        /// </summary>
        public static string PasswordMustMatch {
            get {
                return ResourceManager.GetString("PasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string PayTitle {
            get {
                return ResourceManager.GetString("PayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with portmone.
        /// </summary>
        public static string PayWithPortmone {
            get {
                return ResourceManager.GetString("PayWithPortmone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of clients today.
        /// </summary>
        public static string QuantityOfClientCurrentDay {
            get {
                return ResourceManager.GetString("QuantityOfClientCurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of clients this week.
        /// </summary>
        public static string QuantityOfClientThisWeek {
            get {
                return ResourceManager.GetString("QuantityOfClientThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training records.
        /// </summary>
        public static string RecordsTitle {
            get {
                return ResourceManager.GetString("RecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume subscription.
        /// </summary>
        public static string ResumeSubscription {
            get {
                return ResourceManager.GetString("ResumeSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want resume your subscription?.
        /// </summary>
        public static string ResumeSubscriptionQuenstion {
            get {
                return ResourceManager.GetString("ResumeSubscriptionQuenstion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select training date and time.
        /// </summary>
        public static string SelectTrainingDateAndTime {
            get {
                return ResourceManager.GetString("SelectTrainingDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your trainer.
        /// </summary>
        public static string SelectYourTrainer {
            get {
                return ResourceManager.GetString("SelectYourTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription end date.
        /// </summary>
        public static string SubscriptionEndDate {
            get {
                return ResourceManager.GetString("SubscriptionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze subscription.
        /// </summary>
        public static string SubscriptionFreeze {
            get {
                return ResourceManager.GetString("SubscriptionFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription status.
        /// </summary>
        public static string SubscriptionStatus {
            get {
                return ResourceManager.GetString("SubscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription type.
        /// </summary>
        public static string SubscriptionType {
            get {
                return ResourceManager.GetString("SubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscroption type.
        /// </summary>
        public static string SubscroptionType {
            get {
                return ResourceManager.GetString("SubscroptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful payment.
        /// </summary>
        public static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training date.
        /// </summary>
        public static string TrainingDate {
            get {
                return ResourceManager.GetString("TrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful payment.
        /// </summary>
        public static string UnsuccessfulPayment {
            get {
                return ResourceManager.GetString("UnsuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VerificationСode {
            get {
                return ResourceManager.GetString("VerificationСode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your info.
        /// </summary>
        public static string YourInfo {
            get {
                return ResourceManager.GetString("YourInfo", resourceCulture);
            }
        }
    }
}
